#include<glib.h>
#include<stdlib.h>

void* down()
{
 	FILE *file=fopen("/tmp/aggiornamento.txt","w");/*file temporaneo*/
	CURL *curl;
	CURLcode res=0;
	curl=curl_easy_init();
	if(curl)
		{
		curl_easy_setopt(curl,CURLOPT_URL,"http://www.estrazionidellotto.com/estrazionidellotto.txt");
		curl_easy_setopt(curl,CURLOPT_WRITEDATA,file);
		res=curl_easy_perform(curl);/*download aggiornamento*/
		curl_easy_cleanup(curl);
		}
	fclose(file);
	if(res==0)
	{
		char buff[200];
		file=fopen("/tmp/aggiornamento.txt","r");
		/*saltare le prime 3 righe*/
		for(int i=0;i<3;i++)
		{
			fgets(buff,200,file);
		}
        buff[0]='0';
		char *ErrMsg = 0;
		sqlite3 *db;
		char *home;
		home=getenv("HOME");
		char path[strlen(home)+26];
		sprintf(path,"%s%s",home,"/.lotto4linux/memoria.db");
		char *database=path;
		sqlite3_open(database, &db);
		sqlite3_exec(db,"BEGIN TRANSACTION",NULL,NULL,&ErrMsg);
		sqlite3_exec(db, "PRAGMA journal_mode = MEMORY", NULL, NULL, &ErrMsg);
        sqlite3_exec(db, "PRAGMA synchronous = OFF", NULL, NULL, &ErrMsg);
		char d[3],m[3],a[5],uno[3],due[3],tre[3],quattro[3],cinque[3],query[60];
		int i=0;
		while(buff[0]!='D')
		{
		        fgets(buff,200,file);
   		        /*DATA ESTRAZIONE*/
	        	sprintf(d,"%c%c",buff[0],buff[1]);
	        	sprintf(m,"%c%c",buff[3],buff[4]);
	        	sprintf(a,"%c%c%c%c",buff[6],buff[7],buff[8],buff[9]);

	        	sprintf(uno,"%c%c",buff[15],buff[16]);
	        	sprintf(due,"%c%c",buff[18],buff[19]);
	        	sprintf(tre,"%c%c",buff[21],buff[22]);
	        	sprintf(quattro,"%c%c",buff[24],buff[25]);
	        	sprintf(cinque,"%c%c",buff[27],buff[28]);
        		strcpy(query,"insert into bari values(");
        		strcat(query,d);
        		strcat(query,","); 
        		strcat(query,m);
        		strcat(query,",");      
       		 	strcat(query,a);
        		strcat(query,",");    
        		strcat(query,uno);
        		strcat(query,",");
        		strcat(query,due);
        		strcat(query,",");
        		strcat(query,tre);
        		strcat(query,",");
        		strcat(query,quattro);
        		strcat(query,",");
        		strcat(query,cinque);
        		strcat(query,")");
			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
			i++;
		      	sprintf(uno,"%c%c",buff[30],buff[31]);
		        sprintf(due,"%c%c",buff[33],buff[34]);
		        sprintf(tre,"%c%c",buff[36],buff[37]);
		        sprintf(quattro,"%c%c",buff[39],buff[40]);
		        sprintf(cinque,"%c%c",buff[42],buff[43]);
	        	strcpy(query,"insert into cagliari values(");
	        	strcat(query,d);
	        	strcat(query,","); 
	        	strcat(query,m);
	        	strcat(query,",");      
	        	strcat(query,a);
	        	strcat(query,",");    
	        	strcat(query,uno);
	        	strcat(query,",");
	        	strcat(query,due);
	        	strcat(query,",");
		       	strcat(query,tre);
        		strcat(query,",");
	       	 	strcat(query,quattro);
	        	strcat(query,",");
        		strcat(query,cinque);
	        	strcat(query,")");
	        sqlite3_exec(db, query, NULL, 0, &ErrMsg);
	        i++;
		        sprintf(uno,"%c%c",buff[45],buff[46]);
		        sprintf(due,"%c%c",buff[48],buff[49]);
		        sprintf(tre,"%c%c",buff[51],buff[52]);
		        sprintf(quattro,"%c%c",buff[54],buff[55]);
		        sprintf(cinque,"%c%c",buff[57],buff[58]);
        		strcpy(query,"insert into firenze values(");
        		strcat(query,d);
        		strcat(query,","); 
        		strcat(query,m);
        		strcat(query,",");      
        		strcat(query,a);
		        strcat(query,",");    
	        	strcat(query,uno);
	        	strcat(query,",");
	        	strcat(query,due);
	        	strcat(query,",");
	        	strcat(query,tre);
	        	strcat(query,",");
	        	strcat(query,quattro);
	        	strcat(query,",");
	        	strcat(query,cinque);
	        	strcat(query,")");
			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
			i++;
		        sprintf(uno,"%c%c",buff[60],buff[61]);
		        sprintf(due,"%c%c",buff[63],buff[64]);
		        sprintf(tre,"%c%c",buff[66],buff[67]);
		        sprintf(quattro,"%c%c",buff[69],buff[70]);
		        sprintf(cinque,"%c%c",buff[72],buff[73]);
	        	strcpy(query,"insert into genova values(");
	        	strcat(query,d);
	        	strcat(query,","); 
	        	strcat(query,m);
	        	strcat(query,",");      
	        	strcat(query,a);
        		strcat(query,",");    
        		strcat(query,uno);
        		strcat(query,",");
	        	strcat(query,due);
	        	strcat(query,",");
	        	strcat(query,tre);
	        	strcat(query,",");
	        	strcat(query,quattro);
	        	strcat(query,",");
	        	strcat(query,cinque);
	        	strcat(query,")");
			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
			i++;
			    sprintf(uno,"%c%c",buff[75],buff[76]);
		        sprintf(due,"%c%c",buff[78],buff[79]);
		        sprintf(tre,"%c%c",buff[81],buff[82]);
		        sprintf(quattro,"%c%c",buff[84],buff[85]);
		        sprintf(cinque,"%c%c",buff[87],buff[88]);
	        	strcpy(query,"insert into milano values(");
	        	strcat(query,d);
	        	strcat(query,","); 
	        	strcat(query,m);
	        	strcat(query,",");      
	        	strcat(query,a);
	        	strcat(query,",");    
	        	strcat(query,uno);
	        	strcat(query,",");
	        	strcat(query,due);
	        	strcat(query,",");
	        	strcat(query,tre);
	        	strcat(query,",");
	        	strcat(query,quattro);
	        	strcat(query,",");
	        	strcat(query,cinque);
	        	strcat(query,")");
			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
			i++;
			    sprintf(uno,"%c%c",buff[90],buff[91]);
		        sprintf(due,"%c%c",buff[93],buff[94]);
		        sprintf(tre,"%c%c",buff[96],buff[97]);
		        sprintf(quattro,"%c%c",buff[99],buff[100]);
		        sprintf(cinque,"%c%c",buff[102],buff[103]);
	        	strcpy(query,"insert into napoli values(");
        		strcat(query,d);
        		strcat(query,","); 
	        	strcat(query,m);
        		strcat(query,",");      
        		strcat(query,a);
       	 		strcat(query,",");    
        		strcat(query,uno);
        		strcat(query,",");
        		strcat(query,due);
        		strcat(query,",");
        		strcat(query,tre);
        		strcat(query,",");
        		strcat(query,quattro);
        		strcat(query,",");
        		strcat(query,cinque);
        		strcat(query,")");
 			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
 			i++;
	        	sprintf(uno,"%c%c",buff[105],buff[106]);
		        sprintf(due,"%c%c",buff[108],buff[109]);
		        sprintf(tre,"%c%c",buff[111],buff[112]);
	        	sprintf(quattro,"%c%c",buff[114],buff[115]);
		        sprintf(cinque,"%c%c",buff[117],buff[118]);
        		strcpy(query,"insert into palermo values(");
        		strcat(query,d);
	        	strcat(query,","); 
        		strcat(query,m);
        		strcat(query,",");      
	        	strcat(query,a);
        		strcat(query,",");    
        		strcat(query,uno);
	        	strcat(query,",");
        		strcat(query,due);
        		strcat(query,",");
	        	strcat(query,tre);
        		strcat(query,",");
        		strcat(query,quattro);
	        	strcat(query,",");
        		strcat(query,cinque);
        		strcat(query,")");
			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
			i++;
		       	sprintf(uno,"%c%c",buff[120],buff[121]);
		        sprintf(due,"%c%c",buff[123],buff[124]);
		        sprintf(tre,"%c%c",buff[126],buff[127]);
	        	sprintf(quattro,"%c%c",buff[129],buff[130]);
	        	sprintf(cinque,"%c%c",buff[132],buff[133]);
	        	strcpy(query,"insert into roma values(");
        		strcat(query,d);
	        	strcat(query,","); 
        		strcat(query,m);
        		strcat(query,",");      
	        	strcat(query,a);
        		strcat(query,",");    
	        	strcat(query,uno);
        		strcat(query,",");
        		strcat(query,due);
	        	strcat(query,",");
        		strcat(query,tre);
        		strcat(query,",");
	        	strcat(query,quattro);
        		strcat(query,",");
        		strcat(query,cinque);
	        	strcat(query,")");
			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
			i++;
	        	sprintf(uno,"%c%c",buff[135],buff[136]);
		        sprintf(due,"%c%c",buff[138],buff[139]);
		        sprintf(tre,"%c%c",buff[141],buff[142]);
	        	sprintf(quattro,"%c%c",buff[144],buff[145]);
		        sprintf(cinque,"%c%c",buff[147],buff[148]);
        		strcpy(query,"insert into torino values(");
        		strcat(query,d);
	        	strcat(query,","); 
        		strcat(query,m);
        		strcat(query,",");      
	        	strcat(query,a);
        		strcat(query,",");    
        		strcat(query,uno);
        		strcat(query,",");
	        	strcat(query,due);
        		strcat(query,",");
        		strcat(query,tre);
        		strcat(query,",");
        		strcat(query,quattro);
	        	strcat(query,",");
        		strcat(query,cinque);
        		strcat(query,")");
			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
			i++;
	        	sprintf(uno,"%c%c",buff[150],buff[151]);
	        	sprintf(due,"%c%c",buff[153],buff[154]);
	        	sprintf(tre,"%c%c",buff[156],buff[157]);
	        	sprintf(quattro,"%c%c",buff[159],buff[160]);
	        	sprintf(cinque,"%c%c",buff[162],buff[163]);
        		strcpy(query,"insert into venezia values(");
        		strcat(query,d);
        		strcat(query,","); 
        		strcat(query,m);
        		strcat(query,",");      
        		strcat(query,a);
        		strcat(query,",");    
        		strcat(query,uno);
        		strcat(query,",");
        		strcat(query,due);
        		strcat(query,",");
        		strcat(query,tre);
        		strcat(query,",");
        		strcat(query,quattro);
        		strcat(query,",");
        		strcat(query,cinque);
        		strcat(query,")");
			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
			i++;
				sprintf(uno,"%c%c",buff[165],buff[166]);
	        	sprintf(due,"%c%c",buff[168],buff[169]);
	        	sprintf(tre,"%c%c",buff[171],buff[172]);
	        	sprintf(quattro,"%c%c",buff[174],buff[175]);
	        	sprintf(cinque,"%c%c",buff[177],buff[178]);
        		strcpy(query,"insert into nazionale values(");
        		strcat(query,d);
        		strcat(query,","); 
        		strcat(query,m);
        		strcat(query,",");      
        		strcat(query,a);
        		strcat(query,",");    
        		strcat(query,uno);
        		strcat(query,",");
        		strcat(query,due);
        		strcat(query,",");
        		strcat(query,tre);
        		strcat(query,",");
        		strcat(query,quattro);
        		strcat(query,",");
        		strcat(query,cinque);
        		strcat(query,")");
			sqlite3_exec(db, query, NULL, 0, &ErrMsg);
			i++;
		}	
		sqlite3_exec(db, "END TRANSACTION", NULL, NULL, &ErrMsg);
		sqlite3_close(db);
		printf("Imported %d records\n", i);
		fclose(file);	
		remove("/tmp/aggiornamento.txt");
		storico();
	}
	else
	{
	printf("%s\n","connessione fallita!");
	}
	return 0;
}
